import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/toaster";

import { ThemeProvider } from "../components/theme-provider";
import { GeistSans } from "geist/font/sans";

import { cn } from "@repo/ui/lib/utils";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { auth } from "../../auth";

import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Dark Alpha Capital",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authSession = await auth();
  return (
    <html lang="en" className={cn(GeistSans.variable)}>
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/favicon-48x48.png"
          sizes="48x48"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
        <SessionProvider>
          <main className="parent-container">
            <Header session={authSession} />
            {children}
            <Footer />
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
