import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/toaster";

import { ThemeProvider } from "../components/theme-provider";
import { GeistSans } from "geist/font/sans";

import { cn } from "@repo/ui/lib/utils";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { auth } from "../../auth";

import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authSession = await auth();
  return (
    <html lang="en" className={cn(GeistSans.variable)}>
      <body>
        <SessionProvider>
          <main className="parent-container">
            <Header session={authSession} />
            {children}
            <Footer />
          </main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
