import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/toaster";

import { ThemeProvider } from "./components/theme-provider";
import { GeistSans } from "geist/font/sans";

import { cn } from "@repo/ui/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.variable)}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="parent-container">{children}</main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
