import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/toaster";
import { GeistSans } from "geist/font/sans";

import { cn } from "@repo/ui/lib/utils";

export const metadata: Metadata = {
  title: "Dark Alpha Capital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.variable)}>
      <body>
        <main className="">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
